// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package api

import (
	"errors"
	"fmt"
)

const (
	// ToolCrop is a Tool of type Crop.
	ToolCrop Tool = "crop"
	// ToolHDRMerge is a Tool of type HDRMerge.
	ToolHDRMerge Tool = "hdr_merge"
	// ToolPerspectiveCorrection is a Tool of type PerspectiveCorrection.
	ToolPerspectiveCorrection Tool = "perspective_correction"
	// ToolPortraitCrop is a Tool of type PortraitCrop.
	ToolPortraitCrop Tool = "portrait_crop"
	// ToolStraighten is a Tool of type Straighten.
	ToolStraighten Tool = "straighten"
	// ToolSubjectMask is a Tool of type SubjectMask.
	ToolSubjectMask Tool = "subject_mask"
	// ToolSmoothSkin is a Tool of type SmoothSkin.
	ToolSmoothSkin Tool = "smooth_skin"
)

var ErrInvalidTool = errors.New("not a valid Tool")

// String implements the Stringer interface.
func (x Tool) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Tool) IsValid() bool {
	_, err := ParseTool(string(x))
	return err == nil
}

var _ToolValue = map[string]Tool{
	"crop":                   ToolCrop,
	"hdr_merge":              ToolHDRMerge,
	"perspective_correction": ToolPerspectiveCorrection,
	"portrait_crop":          ToolPortraitCrop,
	"straighten":             ToolStraighten,
	"subject_mask":           ToolSubjectMask,
	"smooth_skin":            ToolSmoothSkin,
}

// ParseTool attempts to convert a string to a Tool.
func ParseTool(name string) (Tool, error) {
	if x, ok := _ToolValue[name]; ok {
		return x, nil
	}
	return Tool(""), fmt.Errorf("%s is %w", name, ErrInvalidTool)
}

// MarshalText implements the text marshaller method.
func (x Tool) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Tool) UnmarshalText(text []byte) error {
	tmp, err := ParseTool(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
